on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew
      - name: Update README.md version
        run: ./gradlew lib:updateReadmeVersion
      - name: Generate Documention with Dokka
        run: ./gradlew lib:dokkaGfm

      # Just saving, there is still a need for automatically creating a Release tag before running this
      #- name: Publish on JitPack
        #run: ./gradlew lib:publish

  wiki:
    needs: dokka
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "lib/build/dokka/gfm/lib"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
