on:
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew
      - name: Update README.md version
        run: ./gradlew lib:updateReadmeVersion
      - name: Generate Documention with Dokka
        run: ./gradlew lib:dokkaGfm
      - name: Moving generated documentation files
        run: |
          rm -rf ./docs
          mv -f lib/build/dokka/gfm/lib ./docs
          mv ./docs/index.md ./docs/Home.md
      - name: Git Commit changes
        run: |
          git add README.md
          git add docs
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Automatic commit" -a
      - name: Git Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          branch: master

