on: 
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate Documention with Dokka
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: lib:dokkaGfm
          
  wiki:
    needs: dokka
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "lib/build/dokka/gfm/lib"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
